import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import appStyles from './app.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="my-5 ml-10 flex items-baseline space-x-4">
          <Link href="/" className={appStyles.link}>
            Home
          </Link>
          <Link href="/notes" className={appStyles.link}>
            Notes
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
